spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace

jwt:
  access-token-key: 9878ec0666bf45a8a60c747a8f8f57069878ec0666bf45a8a60c747a8f8f5706
  refresh-token-key: 97bcb322692044d1a795c82f11ff969697bcb322692044d1a795c82f11ff9696