version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: commerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: commerce_user
      MYSQL_PASSWORD: commerce_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: