spring:
  datasource:
    url: jdbc:mysql://inner-circle-commerce.c74w06weohlm.ap-northeast-2.rds.amazonaws.com:3306/commerce
    username: root
    password: b1ALeR4JgTyBICO3T91y
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace