server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: commerce_user
    password: commerce_password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
#  web:
#    resources:
#      static-locations: classpath:/static/

logging:
  level:
    org.springframework.web: DEBUG
    org.h2: DEBUG
    org.hibernate.SQL: DEBUG